# Generated by Django 5.1.1 on 2024-09-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='humanlity',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='soilMoisture',
            new_name='light',
        ),
    ]
