# Generated by Django 5.1.1 on 2024-09-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_humanlity_sensor_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
